config/routes.rb
Clase::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :pins

  devise_for :users
  get "welcome/index"
  get 'bibloteca' => 'welcome#bibloteca'
  get 'macroeconomia' => 'pins#macroeconomia' 

  root 'welcome#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	def to_param
		"#{id} #{ramo}".parameterize
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show]
  before_filter :authenticate_user!, only: [:show]

  def macroeconomia
    @pins = Pin.all
    # retrieve all Bookmarks ordered by descending creation timestamp
    @pins = Pin.order('created_at desc')
  end

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
    @pins = Pin.order('created_at desc')
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:video, :foto, :ramo, :semestre, :fecha, :profesor, :carrera, :tiempo)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def bibloteca
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta content='width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1' name='viewport'>

  <title>Clases USS</title>

  <link rel="shortcut icon" href="https://cdn3.iconfinder.com/data/icons/social-circle/512/social_4-16.png" type="image/png" />
  
  <meta property='og:locale' content='es_LA'>
  <meta property="og:title" content="Clases USS" />
  <meta property="og:url" content="http://clasesuss.herokuapp.com"/>
  <meta property="og:image" content="http://oi61.tinypic.com/2vws2rl.jpg" />
  <meta property='og:site_name' content='Clases USS' >
  <meta property='og:type' content='website'>
  <meta name='author'content='plus.google.com/113558121163013968974?rel=author'>
  <meta name='description' content='Revive tus clases y sube tus notas estudia donde estés.'>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

  <%= render 'shared/ga' %>

  <%= csrf_meta_tags %>

  <body>
    <%= render 'shared/navbar' %>
    <div style="display:none;">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
    
    <%= render 'shared/uservoice' %>
  </body>
  </html>

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :video %><br>
    <%= f.text_area :video %>
  </div>
  <div class="field">
    <%= f.label :foto %><br>
    <%= f.text_field :foto %>
  </div>
  <div class="field">
    <%= f.label :ramo %><br>
    <%= f.text_field :ramo %>
  </div>
  <div class="field">
    <%= f.label :semestre %><br>
    <%= f.text_field :semestre %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.text_field :fecha %>
  </div>
  <div class="field">
    <%= f.label :profesor %><br>
    <%= f.text_field :profesor %>
  </div>
  <div class="field">
    <%= f.label :carrera %><br>
    <%= f.text_field :carrera %>
  </div>
  <div class="field">
    <%= f.label :tiempo %><br>
    <%= f.text_field :tiempo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<div class="top">
  <h1>Macroeconomía</h1>  
</div>
<div class="container">
  <h1>Listado de videos</h1>
</div>
<div class="container">
  <div class="row">
<% @pins.each do |pin| %>
    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
      <div class=" thumbnail row">
        <div class="poster col-md-3">
          <%= link_to image_tag(pin.foto, :class => 'img-responsive'), pin %>
        </div>
        
        <div class="description  col-md-6">
          <div><h2><%= pin.ramo %></h2></div>

          <p> 
            <span class="sub-description"><strong>Semestre:</strong> <%= pin.semestre %></span>
            <span class="sub-description"><strong>Fecha:</strong> <%= pin.fecha%></span>
          </p>
          <p>
            <span class="sub-description"><strong>Profesor:</strong> <%= pin.profesor %></span>
            <span class="sub-description"><strong>Carrera:</strong> <%= pin.carrera %></span>
          </p>
          <p>
            <span class="sub-description"><strong>Duración:</strong> <%= pin.tiempo %> min.</span>
          </p>
        </div>
      </div>
    </div>
<% end %>
  </div>
</div>

app/views/pins/macroeconomia.html.erb
<div class="top">
  <h1>Macroeconomía</h1>  
</div>

<div class="containerPin">
  <div class="container">
    <h1>Listado de videos</h1>
    <div class="row">
      <% @pins.each do |pin| %>
      <%= link_to(pin) do %>
      <figure class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
        <div class=" thumbnail row">
          <div class="poster col-md-3 col-lg-3 col-sm-3 col-xs-3">
            <%= image_tag(pin.foto, :class => 'img-responsive', :alt => pin.ramo) %>
          </div>
          
          <div class="description col-md-6 col-lg-6 col-sm-9 col-xs-9">
            <div><h2><%= pin.ramo %></h2></div>

            <p> 
              <span class="sub-description"><strong>Semestre:</strong> <%= pin.semestre %></span>
              <span class="sub-description"><strong>Fecha:</strong> <%= pin.fecha%></span>
            </p>
            <p>
              <span class="sub-description"><strong>Profesor:</strong> <%= pin.profesor %></span>
              <span class="sub-description"><strong>Carrera:</strong> <%= pin.carrera %></span>
            </p>
            <p>
              <span class="sub-description"><strong>Duración:</strong> <%= pin.tiempo %> min.</span>
            </p>
          </div>
        </div>
      </figure>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10 col-md-10 col-lg-offset-1 col-md-offset-1">
      <h2>  <%= @pin.ramo %></h2>  
      
      <div class="videoWrapper">
        <%= tag(@pin.video) %>
      </div>
    </div>
  </div>
</div>
<!--
  <div class="paginator">
    <a href="#" class="btn btn-primary pull-left" role="button"><span class="glyphicon glyphicon-step-backward"></span>Anterior</a>
    <a href="#" class="btn btn-primary pull-right" role="button"><span class="glyphicon glyphicon-step-forward"></span>Siguiente</a>
  </div>
-->  




<!--
<p>
  <strong>Video:</strong>
  <%= tag(@pin.video) %>
</p>

<p>
  <strong>Foto:</strong>
  <%= image_tag(@pin.foto) %>
</p>

<p>
  <strong>Ramo:</strong>
  <%= @pin.ramo %>
</p>

<p>
  <strong>Semestre:</strong>
  <%= @pin.semestre %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @pin.fecha %>
</p>

<p>
  <strong>Profesor:</strong>
  <%= @pin.profesor %>
</p>

<p>
  <strong>Carrera:</strong>
  <%= @pin.carrera %>
</p>

<p>
  <strong>Tiempo:</strong>
  <%= @pin.tiempo %>
</p>

-->

app/views/shared/_ga.html.erb
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-50024814-1']);
  _gaq.push(['_setDomainName', 'clasesuss.herokuapp.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if current_user.nil? %> 
        <a class="navbar-brand" href="<%= root_path %>">Clases USS <span class="light">(beta)</span></a>
      <% else %>
        <a class="navbar-brand" href="<%= macroeconomia_path %>">Clases USS <span class="light">(beta)</span></a>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.nil? %> 
          <li><a href="<%= new_user_session_path %>"> Ingreso </a></li>
          <li><a href="<%= new_user_registration_path %>"> Registro </a></li>
        <% else %>
          <li><a href="<%= destroy_user_session_path %>" data-method="delete"> Salir </a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_uservoice.html.erb
<script>
// Include the UserVoice JavaScript SDK (only needed once on a page)
UserVoice=window.UserVoice||[];(function(){var uv=document.createElement('script');uv.type='text/javascript';uv.async=true;uv.src='//widget.uservoice.com/PLFLnz2VOJaRTEdzRlXWA.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(uv,s)})();
UserVoice.push(['set', {
  accent_color: '#448dd6',
  trigger_color: 'white',
  trigger_background_color: 'rgba(46, 49, 51, 0.6)'
}]);
UserVoice.push(['identify', {
  email:      '<% if user_signed_in? %><%= current_user.email %><% end %>',
  created_at: '<% if user_signed_in? %><%= current_user.created_at %><% end %>',
  id:         '<% if user_signed_in? %><%= current_user.sign_in_count %><% end %>',
  type:       'Estudiante',
}]);
UserVoice.push(['addTrigger', { mode: 'contact', trigger_position: 'bottom-right' }]);
UserVoice.push(['autoprompt', {}]);
</script>

app/views/welcome/bibloteca.html.erb
bibloteca.html.erb

app/views/welcome/index.html.erb
<div class="container-fluid all">
	<div class="over">
		<div class="row center">
			<h1>Todos aprendemos de maneras diferentes</h1>
			<div class="wrapperButton">
				<%= button_to "Ver videos", macroeconomia_path, :class => "btn btn-lg btn-goal", :method => :get  %>
				<%= button_to "Registrate", new_user_registration_path, :class => "btn btn-lg btn-second", :method => :get  %>
			</div>
		</div>		
	</div>
	
</div>

app/views/welcome/macroeconomia.html.erb
Hola